### ISSUE TITLE
Text count is too small and background xml not showing

### ISSUE THREAD

**Issue by lekeCoder** [cvoronin/ActionBarMenuItemCounter#1]
@cvoronin: To start with your work is good and it worked. 

But I discovered that the text count was too small and the imageview background xml did not reflect.
What do you think went wrong?

Anticipating your speedy response.
thanks

**Comment by cvoronin** [comment]
Hi, 

counter's text size can be changed in counter_menuitem_layout.xml - just change 

```
<TextView
    android:id="@+id/count"
    android:textSize="8sp"
```

value

**Comment by lekeCoder** [comment]
Thanks. I was able to increase the font size as you said. 
Also, l deleted the imageview and placed my custom background XML on the text view directly and now the background XML is showing as wanted. 

Thanks
